config/routes.rb
Rails.application.routes.draw do

  root 'pictures#index'
  resources :pictures
  resources :comments 
  resources :likes  

  resources :users
  resources :sessions

get "sign_in" => "authentication#sign_in"
get "signed_out" => "authentication#signed_out"
get "change_password" => "authentication#change_password"
get "forgot_password" => "authentication#forgot_password"
get "new_user" => "authentication#new_user"
get "password_sent" => "authentication#password_sent"

post "sign_in" => "authentication#login"

post "new_user" => "authentication#register"
get "account_settings" => "authentication#account_settings"
put "account_settings" => "authentication#set_account_info"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :picture
	belongs_to :user
end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :picture
	belongs_to :user
end

app/models/picture.rb
class Picture < ActiveRecord::Base
	has_many :comments 
	has_many :likes
	has_many :reviews
	has_many :users, through: :comments

	mount_uploader :image, AvatarUploader
end

app/models/user.rb
class User < ActiveRecord::Base

    has_secure_password
  
  has_many :reviews
    has_many :products, through: :reviews
    
    validates :name, presence: true
  mount_uploader :avatar, AvatarUploader

end
  	



  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  	protect_from_forgery with: :exception
	

	  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user


   def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_path
    end
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		# binding.pry
		@comment = Comment.new(comment_params)
		if @comment.save
			redirect_to picture_path(@comment.picture) 
		else
			render :new
		end
	end

	

	private
	def comment_params
		params.require(:comment).permit(:comments, :picture_id)
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController


	def create
		# binding.pry
			@like = Like.new(like_params)
			if @like.save
				redirect_to picture_path(@like.picture) 
			else
				render :new
			end
		end

	
	def count
		@likes =Like.count
	end

	private
	def like_params
		params.require(:like).permit(:like, :picture_id)
	end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

	def index 
		@pictures = Picture.order(created_at: :desc)
	end

	def new
		@picture = Picture.new
	end

	def create
		@picture = Picture.new(picture_params)
		if @picture.save
			redirect_to pictures_url
		else
			render :new
		end
	end

	def show 
		@picture = Picture.find(params[:id].to_i)
		@comment = Comment.new(picture_id: @picture.id)

	end

	def update
		@picture = Picture.find(params[:id].to_i)
		if @picture.update_attributes(picture_params)
			redirect_to "/pictures/#{@picture.id}"
		else
			render :edit
		end
	end

	def destroy
		@picture = Picture.find(params[:id])
		@picture.destroy
		redirect_to pictures_url
	end

	def edit
		@picture = Picture.find(params[:id].to_i)
	end



	private
	def picture_params
		params.require(:picture).permit(:artist, :title, :image, :url)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_url, :notice => "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end

  end

  def destroy
  	session[:user_id] = nil
    redirect_to products_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@users =User.new
  end

  def edit
  	@product = Picture.find(params[:id])

  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to picture_url
  	else
  		render "new"
  	end
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update_attributes(user_params)
  		redirect_to user_path(@user)
  	else
  		render :edit
  	end
  end

  def destroy
  	@user = User.find(params[:id])
  	@user.destroy
  	redirect_to picture_path
  end


  private
  	def user_params
  	 	params.require(:user).permit(:email, :password, :password_confirmation, :name, :avatar)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper



end

app/helpers/authentication_helper.rb
module AuthenticationHelper
end

app/helpers/commments_helper.rb
module CommmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper


end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/authentication/change_password.html.erb
change_password.html.erb

app/views/authentication/new_user.html.erb
<p>Sign Up</p>
<%= form_for @user, :as => :user, :url => new_user_path, :method => :put do |f| %>
  <p>
    <%= f.label 'username:' %><br/>
    <%= f.text_field :username %>
    <%= show_field_error(@user, :username) %>
  </p>
  <p>
    <%= f.label 'email:' %><br/>
    <%= f.text_field :email %>
    <%= show_field_error(@user, :email) %>
  </p>
  <p>
    <%= f.label 'password:' %><br/>
    <%= f.password_field :password %>
    <%= show_field_error(@user, :password) %>
  </p>
  <p>
    <%= f.label 'password confirmation:' %><br/>
    <%= f.password_field :password_confirmation %>
    <%= show_field_error(@user, :password_confirmation) %>
  </p>
  <p>
    <%= f.submit 'Sign Up' %>&nbsp;&nbsp;&nbsp;
    <%= f.submit 'Clear Form', :type => 'reset' %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<p class="userinfo">

      <% if current_user %>
        Signed in as <%= current_user.email %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
          <%= link_to "Profile", current_user %> 
      <% else %>
        <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
      <% end %>
</p>

  <title>Photogur</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>




<body>
<div class ="camera">
<img src="https://fbcdn-sphotos-g-a.akamaihd.net/hphotos-ak-xpa1/v/t1.0-9/10393957_10152595656120342_400159838233260410_n.jpg?oh=7a6b17467206b6b0f47c7659af283a76&oe=54712F58&__gda__=1416511794_12f2f4225a2d669bfdf9c6d2a9eb61da">
</div>

<div class ="nav">
<%= link_to "Home", "/" %> | <%= link_to "New Picture", "/pictures/new" %> | <%= link_to "Top Photos", "/pictures/new" %> 
</div>


<% if flash[:notice] %>
      <p id="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p id="alert"><%= flash[:alert] %></p>
<% end %>


<%= yield %>



<%= yield %>

</body>
</html>

app/views/likes/destroy.js.erb
$('#picture-<%= @picture.id %>').removeClass('liked');

app/views/likes/update.js.erb
$('#picture-<%= @picture.id %>').addClass('liked');

app/views/pictures/edit.html.erb
<h1> Edit </h1>
<p> <%= link_to "back", @picture %> </p>
<%= form_for @picture do |f| %>
	<p><%= f.label "artist" %><br><%= f.text_field "artist"%></p>
	<p><%= f.label "title" %><br><%= f.text_field "title"%></p>
	<p><%= f.label "url" %><br><%= f.text_field "url"%></p>
  	<p><%= f.file_field "image" %></p>

	<p><%= submit_tag "Save" %></p>
<%end%>

app/views/pictures/index.html.erb
<div class="gridwrapper">
	
			<% @pictures.each do |picture| %>
				<div class="tile">
					<div class="tileinner">
						<%= link_to image_tag(picture.url), "/pictures/#{picture.id}" %>
						<%= link_to image_tag(picture.image), "/pictures/#{picture.id}" %>
			
					</div>
				</div>
			<%end%>
</div>

app/views/pictures/new.html.erb
<h1> New Photo </h1>

<%= form_for @picture do |f| %>
	<p><%=f.label "artist" %><br><%=f.text_field "artist"%></p>
	<p><%=f.label "title" %><br><%=f.text_field "title"%></p>
	<p><%=f.label "url" %><br><%=f.text_field "url"%></p>
	<p><%= f.file_field "image" %></p>
	<p><%=submit_tag "Save" %></p>
<%end%>
		

app/views/pictures/show.html.erb
<h1> Picture </h1>

<%= link_to "Back to Pictures", pictures_url %> | <%= link_to "Edit", edit_picture_path(@picture) %> | 
<%= link_to "Delete", @picture, :confirm => "Are you sure you want to delete this picture?", :method => :delete %>

<p> <%= @picture.title %>, <%=@picture.artist %></p>
<% unless @picture.url.blank? %>
	<img src= "<%= @picture.url %>"> 
<% end %>
<% unless @picture.image.blank? %>
	<img src= "<%= @picture.image.url %>"> 
<% end %>




<%= form_for @comment do |f| %>
	<%= f.hidden_field :picture_id %>
	<p><%= f.label "comments" %><br><%= f.text_field "comments"%></p>
	<p><%= submit_tag "Save" %></p>

	
<%end%>
<h2> Comments </h2>
 <%=@picture.comments.each do |picture|%>

	<p><%= picture[:comments]%></p>
	<%end%>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for (@users) do |f| %>

	<div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :avatar%><br/>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/users/show.html.erb
<h1> Profile </h1>

<%= link_to "Back to Products", products_url %>  | 



    
    <p class="userinfo">

      <% if current_user %>
       Email: <%= current_user.email %>.<br>
       Username: <%= current_user.name%>.<br>
       Image:  <img src= "<%= current_user.avatar.url %>"> 
      <% end %>
</p>